version: '3.8'
name: dev-database-app
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '..:/workspaces:cached'
    command: sleep infinity
    networks:
      - devnet
    depends_on:
      - db
      - redis
  db:
    image: "postgres:latest"
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - devnet
  redis:
    image: "redis:latest"
    restart: unless-stopped
    networks:
      - devnet
volumes:
  postgres-data: null

networks:
  devnet:
    driver: bridge